export { DefaultPage } from "./default";
export { CheatsPage } from "./server/cheats";
export { GamesPage } from "./server/games";
export { VideosPage } from "./server/videos";
export { ReviewsPage } from "./client/reviews";
export { MiscPage } from "./server/misc";
export { VipCheatsPage } from "./client/vip-cheats";
export { SemiVipCheatsPage } from "./client/semivip-cheats";
export { PartnersPage } from "./server/partners";
